### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by bikallem** [tkob/proglr#1]
Hi,
Is there any documentation on using the parser?

**Comment by tkob** [comment]
Thank you for the interest in Proglr.

First, the README serves as 'Getting Started with Calc Example'.

The grammar of syntax definition is basically ABNF of [BNFC](http://bnfc.digitalgrammars.com/) converter. So BNFC's reference manual will help a lot.

For more complex example, see https://gist.github.com/tkob/cd174de0cbe263de3f8e , which is an implementation of a small compiler. Another living example is [UXML](https://github.com/tkob/uxml), which is an XML parser.

Please let me know if you have anything unclear about Proglr.

**Comment by bikallem** [comment]
:+1: Thank you for the pointer. Maybe we could put this information in the repo wiki here.
